name: Build and Publish .NET MAUI Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-maui:
    strategy:
      fail-fast: false
      matrix:
        os: [windows-latest, macos-13] # Compila no Windows e macOS para diferentes plataformas

    runs-on: ${{ matrix.os }}

    env:
      PROJECT_FILE: mdi-maui/mdi-maui.csproj
      BUILD_CONFIGURATION: Release
      BUILD_VERSION: 1.0.${{ github.run_number }}

    steps:
    # Checkout do código
    - name: Checkout do repositório
      uses: actions/checkout@v4

    # Instalação do .NET SDK
    - name: Instalar .NET SDK 8.0.11
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.11

    # Instalação da Workload MAUI
    - name: Instalar .NET MAUI Workload
      run: dotnet workload install maui --ignore-failed-sources

    # Configuração do Xcode no macOS
    - name: Configurar Xcode (macOS)
      if: runner.os == 'macOS'
      uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: "14.3"

    # Restaurar dependências do projeto
    - name: Restaurar dependências
      run: dotnet restore ${{ env.PROJECT_FILE }}

    # Compilar o projeto
    - name: Compilar o projeto
      run: dotnet build ${{ env.PROJECT_FILE }} --configuration ${{ env.BUILD_CONFIGURATION }} --no-restore

    # Publicação do app para as plataformas relevantes
    - name: Publicar Windows
      if: runner.os == 'Windows'
      run: dotnet publish ${{ env.PROJECT_FILE }} -c ${{ env.BUILD_CONFIGURATION }} -f net8.0-windows -o ./publish/windows

    - name: Publicar Android
      run: dotnet publish ${{ env.PROJECT_FILE }} -c ${{ env.BUILD_CONFIGURATION }} -f net8.0-android -o ./publish/android

    - name: Publicar iOS (macOS)
      if: runner.os == 'macOS'
      run: dotnet publish ${{ env.PROJECT_FILE }} -c ${{ env.BUILD_CONFIGURATION }} -f net8.0-ios /p:ArchiveOnBuild=true -o ./publish/ios

    # Upload dos artefatos compilados
    - name: Upload Artefatos - Windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v3
      with:
        name: MauiGnome-Windows
        path: ./publish/windows

    - name: Upload Artefatos - Android
      uses: actions/upload-artifact@v3
      with:
        name: MauiGnome-Android
        path: ./publish/android

    - name: Upload Artefatos - iOS
      if: runner.os == 'macOS'
      uses: actions/upload-artifact@v3
      with:
        name: MauiGnome-iOS
        path: ./publish/ios
